### ISSUE TITLE
Form field with number property will create an array rather than an object

### ISSUE THREAD

**Issue by lvqq** [arco-design/arco-design#574]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.29.1
- **System:** macOS
- **Browser:** chrome97.0.4692.99
- **Reproduction Link:** https://codesandbox.io/s/suspicious-mclean-ku36ez?file=/src/App.js

## What is expected?
Form value should be { a: "1", b: { "4": "2" } } 

## Steps to reproduce
1. Input "1","2" and submit
2. Form value will be { a: "1", b: [undefined, undefined, undefined, undefined, "2"] } 

![image](https://user-images.githubusercontent.com/29809148/155140781-71d4cf31-0a0f-4fe6-9e3d-02840fa4f6fd.png)

**Comment by chenc041** [comment]
This bug was caused by `lodash.set` function and The temporary solution is to avoid using numbers as keys I will try to resolve this bug at lodash project.

[try REPL](https://lodash.com/docs/4.17.15#set)

<img width="1503" alt="截屏2022-02-22 23 54 18" src="https://user-images.githubusercontent.com/16097887/155169740-aa876338-0dac-41f9-a232-102510cb9158.png">
