### ISSUE TITLE
Collapse组件在React18中开启StrictMode后报错

### ISSUE THREAD

**Issue by AruSeito** [arco-design/arco-design#858]
- [ x ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.32.2
- **Framework version:** React
- **Browser:** chrome101.0.4951.64
- **Reproduction Link:** https://codesandbox.io/s/jolly-water-4ji6dp

## Extra info
https://github.com/reactwg/react-18/discussions/19

## Steps to reproduce
在18中开启StrictMode后报错，详见可复现链接。
在17中开启StrictMode后正常。

**Comment by 0x67cq** [comment]
遇到相同问题

**Comment by moonrailgun** [comment]
Same question, and checked source code and find React with entry into this scope

https://github.com/arco-design/arco-design/blob/588a3e4412bc03e9dbebe6888232792ec1f98de9/components/_util/hooks/useMergeValue.ts#L18-L31

Although value of `value` in context will always be `undefined`. because of future feature:
> In the future, we’d like to add a feature that allows React to add and remove sections of the UI while preserving state. For example, when a user tabs away from a screen and back, React should be able to immediately show the previous screen. To do this, React will support remounting trees using the same component state used before unmounting.

I think its a hidden trouble in future.

my problem is why `useMergeValue` will set will `undefined` not `defaultStateValue` ? 

-------

BTW, here is a duplicated issue: https://github.com/arco-design/arco-design/issues/1472
